### DISCUSSION TITLE
Trouble with LDAP Configuration

### DISCUSSION THREAD

**Discussion by lockedandlogan** [mitre/caldera#2987] [Q&A]
Has anyone successfully gotten LDAP authentication working that could lend a hand? 

In Caldera, I have the following (sensitive info removed):

```
ldap:
        dn: DN of the ou where the account lives
        server: ldaps://10.x.x.x:636
        user_attr: sAMAccountName
        group_attr: objectClass
        red_group: user
```

No matter what I do, I am not having any success getting it to accept credentials. I added some additional logging to `default.py` and confirmed that the bind is what is failing. 

I put together a short python script recreating the parameters used in Caldera and get the same result, until I change the username to the format `domain\samaccountname`, after which I am able to successfully bind. 

Ldap3 documentation seems to indicate that `domain\samaccountname` is the required format for the `user` parameter for a connection, so I am a bit perplexed by Caldera's `user_string` format that it is passing. I'm sure I'm missing something, just not sure what else to try. 

Thanks in advance for anyone who is able to help out!
