### ISSUE TITLE
Question: Create a regex parser.

### ISSUE THREAD

**Issue by 0xThiebaut** [mitre/caldera#1265]
This is a follow-up on #1210.

I currently have the following code aimed at the 1.5.1 version. Could you tell me why the parser is not working?

I created an ability relying on the variable I expected to extract to confirm the role did not extract it as expected.

`caldera/data/parsers/regex.py`

```python
from app.objects.c_relationship import Relationship
from plugins.stockpile.app.parsers.base_parser import BaseParser

class Parser(BaseParser):

    def parse(self, blob):
        relationships = []
        for mp in self.mappers:
            if 'regex' not in dir(mp):
                continue
            for match in re.findall(mp.regex):
                source = self.set_value(mp.source, match, self.used_facts)
                target = self.set_value(mp.target, match, self.used_facts)
                relationships.append(
                    Relationship(source=(mp.source, source),
                                 edge=mp.edge,
                                 target=(mp.target, target))
                )
        return relationships
```

`caldera/data/abilities/credential-access/d4df3433-4828-4cba-a213-0f2f2ce2e162.yml`

```yaml
---

- id: d4df3433-4828-4cba-a213-0f2f2ce2e163
  name: Test Regex Parser
  description: Test Regex Parser
  tactic: credential-access
  technique:
    attack_id: T0000
    name: Testing
  platforms:
    linux:
      sh:
        command: |
          echo Hello
        parsers:
          data.parsers.regex:
            - source: sample
              regex: ".*"
```

Thanks in advance for any help and pointers!
