### ISSUE TITLE
Ability.display() differs from the format in the yaml files

### ISSUE THREAD

**Issue by zaphodef** [mitre/caldera#1505]
When calling `Ability.display()`, we get a dict which is not formated in the same way that we store abilities in yaml (see below). Not sure if the format should be changed to match the syntax expected in the yaml config files (that would need other fixes elsewhere, when `Ability.display()` is used), or if we should add another method like `as_yaml()`? This would allow to easily store an ability from within the Python backend (which I'm currently looking for, working on the "atomic" plugin).

The only conversion into the format used in yaml files looks to be in the WebUI ([in profiles.html](../blob/master/templates/profiles.html#L244))

`Ability.display()` will return something like:
```yaml
- ability_id: TEST-ID
  access: 0
  cleanup: []
  description: ''
  executor: ''
  id: TEST-IDNoneNone
  name: ''
  parsers: []
  payloads: []
  platform: ''
  privilege: ''
  requirements: []
  tactic: test
  technique_id: T-test
  technique_name: ''
  test: ''
  timeout: 60
  unique: TEST-IDNoneNone
  variations: []
```

while abilities are stored in `data/abilities/*.yml` as
```yaml
- description: Test
  id: TEST-ID
  name: Test
  platforms:
    darwin:
      sh:
        command: echo "TEST"
    linux:
      sh:
        command: echo "TEST"
  tactic: test
  technique:
    attack_id: T-test
    name: Test
```
