### ISSUE TITLE
Question regarding ability "WMIC Process Enumeration"

### ISSUE THREAD

**Issue by crud3** [mitre/caldera#1609]
Hi all, I have a question about the Caldera ability "WMIC Process Enumeration" with the id `94f21386-9547-43c4-99df-938ab05d45ce`

In its YAML file, it says the following:
```
- id: 94f21386-9547-43c4-99df-938ab05d45ce
  name: WMIC Process Enumeration
  description: Capture process id, executable path, pid and parent pid before writing to disk
  tactic: collection
  technique:
  attack_id: T1047
  name: WMIC
```
So the ability is grouped into the tactic _Collection_, but the technique it references (T1047) is called "Windows Management Instrumentation" and is only grouped into the tactic _Execution_. Shouldn't the ability then be grouped into the _Execution_ tactic or is it just considered okay if an ability grouped into tactic A implements a technique from tactic B?

Best wishes and thanks in advance!
