### ISSUE TITLE
Question regarding ability "1-min sleep"

### ISSUE THREAD

**Issue by crud3** [mitre/caldera#1610]
Hi all,

I have a question regarding ability `36eecb80-ede3-442b-8774-956e906aff02`

```
- id: 36eecb80-ede3-442b-8774-956e906aff02
  name: 1-min sleep
  description: Pause all operations to avoid making noise
  tactic: defense-evasion
  technique:
      attack_id: T1108
      name: Redundant Access
 platforms:
      darwin:
           sh:
                command: sleep 60
[...]
```
This ability is grouped into the `Defense Evasion` tactic and is described as implementing `Redundant Access`, but all it does is sleep. Is this correct? While sleeping could be useful for defense evasion, I don't really see why/how this implements Redundant Access.

Best wishes
