### ISSUE TITLE
How to add a new technique and ability which not exist on caldera

### ISSUE THREAD

**Issue by lydia-lyly** [mitre/caldera#2124]
**Hello,
currently a student in computer science, we have a research project that focuses on threat intelligence and emulation adversary, currently in the deployment phase we do not find enough documentation knowing that we would like to add techniques and abilities that do not exist on the platform of caldera we do not know if this is possible and if you have answers or avenues for research that would be more than perfect;

thank you in advance for your help

have a good day**

**Comment by kaylakraines** [comment]
Hi @Lydia-lyly! 
You can create a new ability through the CALDERA GUI by navigating to "adversaries" in the lefthand sidebar in CALDERA. Either choose an existing adversary profile, or slide the toggle to "ADD" to add a new adversary profile. Then, click "+ add ability". 
<img width="1116" alt="Screen Shot 2021-04-19 at 10 54 46 AM" src="https://user-images.githubusercontent.com/20597974/115259256-b775fe00-a0ff-11eb-819c-dc2afcaac83c.png">
You can now fill in the information for your new ability and click "Save". 
<img width="927" alt="Screen Shot 2021-04-19 at 10 55 53 AM" src="https://user-images.githubusercontent.com/20597974/115259289-bf35a280-a0ff-11eb-888f-554260d91c08.png">

You can read more about this in the CALDERA documentation here: https://caldera.readthedocs.io/en/latest/Basic-Usage.html#abilities

Alternatively, you can create a new ability by creating a new YML file in `plugins/*/data/abilities/*` (for example, `plugins/stockpile/data/abilities/impact`). You can look at the existing YML files to get an idea of the required format. Once the new file is created, restart CALDERA and you should be able to access the new ability. You can read more about this method here: https://caldera.readthedocs.io/en/latest/Initial-Access-Attacks.html#create-an-ability

Please let us know if you have further questions!

**Comment by lydia-lyly** [comment]
Hi, 

Thank you very much for your answer, I would like to know that once created a new ability on caldera in the .yml file what is the ID field (we assign it randomly?) And the command field where we bring it?

I thank you in advance for your return

cordially

**Comment by kaylakraines** [comment]
That's correct, the ID field is a randomly generated UUID. Are you creating an ability using CALDERA server, or are you creating it by manually writing the YML file? 

If you are creating the ability in CALDERA server, you can generate the randomly created ID by clicking the "generate new id" button on the right side (see the image I posted in the last response). You can add the command by clicked the "add executor" button and then choosing a "platform", "exector", and "command". Once you save the ability, you should be able to find the newly created YML file in data/abilities.

If you are creating the ability by directly writing the YML file, here is an example of what the file could look like:
```
- id: 9a30740d-3aa8-4c23-8efa-d51215e8a5b9
  name: Scan WIFI networks
  description: View all potential WIFI networks on host
  tactic: discovery
  technique:
    attack_id: T1016
    name: System Network Configuration Discovery
  platforms:
    darwin:
      sh:
        command: |
          ./wifi.sh scan
        payload: wifi.sh
    linux:
      sh:
        command: |
          ./wifi.sh scan
        payload: wifi.sh
    windows:
      psh:
        command: |
          .\wifi.ps1 -Scan
        payload: wifi.ps1
```
There is a different "command" for each operating system. In this example, the "commands" are `./wifi.sh scan` or `.\wifi.ps1 -Scan`.

If this doesn't answer your question, feel free to let me know.
