### ISSUE TITLE
asyncio error when running an ability that uses crackmapexec

### ISSUE THREAD

**Issue by Bros10** [mitre/caldera#2199]
Hi, I've came across this error:
![image](https://user-images.githubusercontent.com/25135718/126311296-5b8975cc-7223-4416-aec3-2a53b20fbbed.png)
While attempting to run any crackmapexec commands via an ability, what doesn't make sense is about a week ago all these abilities worked perfectly. Since then I've not changed the command ran nor the machine that the agent is deployed on and still this error appears. I've tried with an elevated agent and still no success. 

I know that crackmapexec still works fine as copying and pasting the command onto the actual machine it runs perfectly, so it seems to be an issue with the agent used.

**Comment by uruwhy** [comment]
@Bros10 Could you provide the caldera version you used to successfully run the ability in the past, as well as the caldera version that caused this error?

**Comment by uruwhy** [comment]
If possible, could you also share the ability YAML file you used to create the ability? Feel free to strip out any personal information if needed.

**Comment by Bros10** [comment]
> @Bros10 Could you provide the caldera version you used to successfully run the ability in the past, as well as the caldera version that caused this error?

May be a stupid question, but is there a nice way to check exactly what version of CALDERA I'm running?  I am pretty sure it's 3.0.0 though

**Comment by Bros10** [comment]
> If possible, could you also share the ability YAML file you used to create the ability? Feel free to strip out any personal information if needed.

```yaml
- id: 5927c6bc-71dc-4c32-b681-6dfe3f487512
  name: LDAP Password spraying against a single user or a list of valid users
  description: Using cme to find valid creds
  tactic: discovery
  technique:
    attack_id: T1018
    name: Remote System Discovery
  platforms:
    linux:
      sh:
        command: crackmapexec ldap 192.168.10.18 -u Administrator -p top_100_passwords.txt
        payloads:
        - top_100_passwords.txt
        - users.txt
        cleanup: rm top_100_passwords.txt
```
