### ISSUE TITLE
Docker container data lost on restart

### ISSUE THREAD

**Issue by psppatrick** [mitre/caldera#2319]
Hi guys, 

I've been trying to get a caldera container which has persistent storage when it's restarted. 
I can get the container to have persistent volumes and storage, but when I restart the container it loses all of the data in it such as the reports, operations and custom abilities added.

Is there something I'm doing wrong with the configuration? 

I'm using docker-compose with a modified version of the compose-file 

```
version: '3'

services:
  caldera:
    image: caldera:latest
    ports:
      - "8888:8888"
      - "7010:7010"
      - "7011:7011/udp"
      - "7012:7012"
    volumes:
      - ./:/usr/src/app
      - /datatesting:/resultinfo
```

My config is as follows

```
api_key_blue: ##removed for privacy
api_key_red: ##removed for privacy
app.contact.dns.domain: mycaldera.caldera
app.contact.dns.socket: 0.0.0.0:8853
app.contact.gist: API_KEY
app.contact.html: /weather
app.contact.http: http://0.0.0.0:8888
app.contact.tcp: 0.0.0.0:7010
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012
crypt_salt: ##removed for privacy
encryption_key: ##removed for privacy
exfil_dir: /tmp/caldera
host: 0.0.0.0
plugins:
- access
- atomic
- compass
- debrief
- fieldmanual
- gameboard
- manx
- response
- sandcat
- stockpile
- training
port: 8888
reports_dir: /resultinfo
requirements:
  go:
    command: go version
    type: installed_program
    version: 1.11
  python:
    attr: version
    module: sys
    type: python_module
    version: 3.6.1
users:
  blue:
    blue: team
  red:
    red: team
    admin: caldera
```
