### ISSUE TITLE
Training Plugin: Add new user does not complete

### ISSUE THREAD

**Issue by cunhaac** [mitre/caldera#2392]
After adding a new user in the red section on local.yml file the challenge does not completed.

I am sure I am using the local.yml file instead of the default.yml without the --inscure or --fresh flag. I can login with the user test.

I already tried with python script and docker-compose version (I remove the flags on the docker-compose.yml file also)

I am stuck on this challenge.

**Comment by cyber-arsenull** [comment]
Hello @cunhaac,
I just ran through this challenge on the current master branch. I didn't run into an issue on this one, so hopefully it is something minor in the config that is giving you issue. Here is what my training looks like when completed:
![image](https://user-images.githubusercontent.com/4370241/146658458-acfb4a31-f9af-4c7a-b1ed-b59dbac270d4.png)

This is my `conf/local.yml` file:
```YML
ability_refresh: 60
api_key_blue: ptSp1vYUKrhGLWUnTZHjmC9WjR77ApOk5G2_3jZHPFM
api_key_red: MlhCu1PwbYzoJu9NaDuGN8WWfQ9PF6vm9sXPd_EGYb8
app.contact.dns.domain: mycaldera.caldera
app.contact.dns.socket: 0.0.0.0:8853
app.contact.ftp.host: 0.0.0.0
app.contact.ftp.port: 2223
app.contact.ftp.pword: caldera
app.contact.ftp.server.dir: ftp_dir
app.contact.ftp.user: caldera_user
app.contact.gist: API_KEY
app.contact.html: /weather
app.contact.http: http://0.0.0.0:8888
app.contact.slack.api_key: SLACK_TOKEN
app.contact.slack.bot_id: SLACK_BOT_ID
app.contact.slack.channel_id: SLACK_CHANNEL_ID
app.contact.tcp: 0.0.0.0:7010
app.contact.tunnel.ssh.host_key_file: REPLACE_WITH_KEY_FILE_PATH
app.contact.tunnel.ssh.host_key_passphrase: REPLACE_WITH_KEY_FILE_PASSPHRASE
app.contact.tunnel.ssh.socket: 0.0.0.0:8022
app.contact.tunnel.ssh.user_name: sandcat
app.contact.tunnel.ssh.user_password: s4ndc4t!
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 127.0.0.1:7012
crypt_salt: Hu53Nht5OAE3Os1XOy0DM1cXCo7MhnAEAxaXuFugZP0
encryption_key: oKLz-a0MRqUgxPSSngvIrLN9MzUFIwi-feQ48sHVTk4
exfil_dir: /tmp/caldera
host: 0.0.0.0
plugins:
- access
- atomic
- compass
- debrief
- fieldmanual
- gameboard
- manx
- response
- sandcat
- stockpile
- training
port: 8888
reports_dir: /tmp
requirements:
  go:
    command: go version
    type: installed_program
    version: 1.11
  python:
    attr: version
    module: sys
    type: python_module
    version: 3.6.1
users:
  blue:
    blue: 2HSOSvNR3zERkz9QUTXUZqK12LPD1ZlXqZHjjvduOAg
  red:
    red: cgJAK8mcjt978-lNT4Hp2AlkktLxS0ulVH9bkfF5ciw
    test: test
```
I used `python .\server.py -l DEBUG` to start the server.

Please let me know how this ends up for you, and if you have issues if you could post the same information that'd be great!
