### ISSUE TITLE
caldera 3.1.0 on Ubuntu. How to add sub-techniques from Red Canary Atomic

### ISSUE THREAD

**Issue by MehanoidRUS** [mitre/caldera#2586]
Hello everyone,
How to add sub-techniques from Red Canary Atomic to caldera?
For example: in Red Canary Atomic there are sub-techniques T1110.001, T1110.002, T1110.003, T1110.004, only T1110.004 is loaded in the caldera.
Thanks for the help.

**Comment by MehanoidRUS** [comment]
I did not find a solution in the documentation, maybe I was looking badly

**Comment by CDJellen** [comment]
Hello @MehanoidRUS ,

You can add new sub-techniques to CALDERA by adding new abilities.

New abilities can be created:
1. Through the UI, under the `abilities` tab in the navigation menu, or
2. By creating a new `<ability uuid>.yml` Ability file in the `/data/abilities/` directory.

When adding a new ability through the UI, you can specify the `command`, `payload`, `tactic` and `technique`.  The technique field accepts either ATT&CK technique ID's (e.g. `T1110`) or sub-technique ID's (e.g. T1110.001`).  Once the new ability is created, the sub-technique will register in CALDERA.

If adding many new abilities, or if you prefer the structure of `.yml` files, you can add new sub-techniques in the `attack_id` field.  I've included a sample from the `stockpile` plugin below, which can serve as a template for adding new Red Canary Atomic abilities.

```yml
- id: 2946edba-54d8-11eb-ae93-0242ac130002
  name: Password Policy for a domain
  description: Password Policy Discovery for a domain
  tactic: discovery
  technique:
    attack_id: T1201
    name: Password Policy Discovery for a domain
  platforms:
    windows:
      psh:
        command: |
          net accounts /domain
```

Please feel free to open a new issue if you run in to any challenges when adding abilities to CALDERA in either of the two methods described above.  Thanks!
