### ISSUE TITLE
Variable

### ISSUE THREAD

**Issue by AndersonLT** [mitre/caldera#284]
I'm try to write a command with a variable, but i was get the same error
Missing: #{command}

The variable was put in facts either.

**Comment by privateducky** [comment]
can you post your full ability? 

several abilities (such as 2fe2d5e6-7b06-4fc0-bf71-6966a1226731) use variables right now, so you'll want to make sure yours looks similar.

additionally, you should try a fresh clone of the code (git clone https://github.com/mitre/caldera.git --recursive) and try your ability in there. i say this because if your plugins are out-of-date, you could get odd behavior.

**Comment by AndersonLT** [comment]
I'm using Atomic Red Team abilities with https://github.com/xenoscr/Atomic-Caldera

A example looks like:
```yaml
- id: 2e943740-b06e-4bea-85dd-bcf4f2080073
  name: Create Account
  description: Creates a new user in Linux and adds the user to the `root` group.
    This technique was used by adversaries during the Butter attack campaign. (Atomic
    Red Team)
  tactic: persistence
  technique:
    attack_id: T1136
    name: Create a new user in Linux with `root` UID and GID.
  executors:
    bash:
      command: |-
        useradd -o -u 0 -g 0 -M -d /root -s /bin/bash #{username}
        echo "#{password}" | passwd --stdin #{username}

```

**Comment by privateducky** [comment]
perfect; ok we're actually working with the owner of that repo to update the schema to match the updates we made inside caldera on the previous version (2.1.0) pin and onward.

your ability file will need to match the schema outlined here: https://github.com/mitre/caldera/wiki/What-is-an-ability%3F

**Comment by privateducky** [comment]
I haven't tested this-- but it looks like this is how your ability file would look:
```
- id: 2e943740-b06e-4bea-85dd-bcf4f2080073
  name: Create accounts
  description: Creates a new user in Linux and adds the user to the `root` group.
    This technique was used by adversaries during the Butter attack campaign. (Atomic
    Red Team)
  tactic: persistence
  technique:
    attack_id: T1136
    name: Create a new user in Linux with root UID and GID.
  executors:
    linux:
      command: |
          useradd -o -u 0 -g 0 -M -d /root -s /bin/bash #{username};
          echo "#{password}" | passwd --stdin #{username}
```
