### ISSUE TITLE
Error starting operation

### ISSUE THREAD

**Issue by perra22** [mitre/caldera#840]
Hi, i've created an adversary and then started an operation (i'm using master branch). It fails with this error:

>  File "/home/ubuntu/stage/caldera/plugins/chain/app/chain_api.py", line 77, in rest_core
    output = await options[request.method][index]data
  File "/home/ubuntu/stage/caldera/plugins/chain/app/chain_svc.py", line 79, in create_operation
    operation = await self._build_operation_object(data)
  File "/home/ubuntu/stage/caldera/plugins/chain/app/chain_svc.py", line 102, in _build_operation_object
    return Operation(name=name, planner=planner[0], agents=agents, adversary=adversary[0],
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/ubuntu/stage/caldera/plugins/chain/app/chain_api.py", line 55, in rest_core
    data = dict(await request.json())
TypeError: 'NoneType' object is not iterable
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 154, in factory
    response = await handler(request)
  File "/home/ubuntu/stage/caldera/plugins/chain/app/chain_api.py", line 40, in rest_full
    base[0]['abilities'] = [a.display for a in await self.data_svc.locate('abilities')]
TypeError: 'NoneType' object is not subscriptable

**Comment by wbooth** [comment]
Looks like the format of the adversary may be slightly off. Double check with an existing adversary that the formatting is the same

**Comment by perra22** [comment]
I've solved it, it was due to the remote.host.ip fact wrong value.
Now when i start my attack:

```
id: 87eb4d51-eb6b-4a1d-8213-4b81cf1d9bb3
name: First Attack 1.1
description: First implementation
phases:
  1:
   - 85341c8c-4ecb-4579-8f53-43e3e91d7617
   - 47abe1f5-55a5-46cc-8cad-506dac8ea6d9
   - 1fb7710e-d0e6-4cef-b760-9cff3dcfdc56
```
the error is:

> ubuntu@caldera-bionic:~/stage$ DEBUG:app_svc:Starting operation: rookie#1.1
DEBUG:planning_svc:Generated 3 links for 460037
Traceback (most recent call last):
  File "/home/ubuntu/stage/caldera_bleeding_edge/app/service/app_svc.py", line 91, in run_operation
    await planner.execute(phase)
  File "/home/ubuntu/stage/caldera_bleeding_edge/plugins/stockpile/app/sequential.py", line 8, in execute
    for link in await self.planning_svc.get_links(operation=self.operation, phase=phase):
  File "/home/ubuntu/stage/caldera_bleeding_edge/app/service/planning_svc.py", line 33, in get_links
    links.extend(await self._generate_and_trim_links(agent, operation, abilities, link_status, trim))
  File "/home/ubuntu/stage/caldera_bleeding_edge/app/service/planning_svc.py", line 75, in _generate_and_trim_links
    agent_links = await self.trim_links(operation, agent_links, agent)
  File "/home/ubuntu/stage/caldera_bleeding_edge/app/utility/base_planning_svc.py", line 23, in trim_links
    links[:] = await self.add_test_variants(links, agent, operation)
  File "/home/ubuntu/stage/caldera_bleeding_edge/app/utility/base_planning_svc.py", line 48, in add_test_variants
    copy_link = copy.deepcopy(link)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

Thanks for the help!

**Comment by perra22** [comment]
The problem was inside the ability 47abe1f5-55a5-46cc-8cad-506dac8ea6d9:
```
---

- id: 47abe1f5-55a5-46cc-8cad-506dac8ea6d9
  name: Scan IP for ports
  description: Use dropped scanner to find open popular ports
  tactic: discovery
  technique:
    attack_id: T1046
    name: Network Service Scanning
  platforms:
    darwin:
      sh:
        command: |
          python scanner.py -i #{remote.host.ip}
        parsers:
          plugins.stockpile.app.parsers.scan:
            - source: remote.host.ip#
              edge: has_open_port
              target: remote.host.port
        payload: scanner.py
    linux:
      sh:
        command: python scanner.py -i #{remote.host.ip}
        parsers:
          plugins.stockpile.app.parsers.scan:
            - source: remote.host.ip
              edge: has_open_port
              target: remote.host.port
        payload: scanner.py

```
i've modified the command with python3 instead of pyhton:
   ```
 linux:
      sh:
        command: python3 scanner.py -i #{remote.host.ip}
        parsers:
          plugins.stockpile.app.parsers.scan:
            - source: remote.host.ip
              edge: has_open_port
              target: remote.host.port
        payload: scanner.py
```
