### ISSUE TITLE
Variable not filled with fact

### ISSUE THREAD

**Issue by perra22** [mitre/caldera#843]
Hi, i've created a new ability that implement [T1087](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1087/T1087.md#atomic-test-1---enumerate-all-accounts) with a variable called #{host.user.accounts} that represent the path to the file where redirect the output of the command:

```
---
- id: 1fb7710e-d0e6-4cef-b760-9cff3dcfdc56
  name: Enumerate all accounts
  description: Enumerate all accounts by copying /etc/passwd to another file
  tactic: discovery
  technique:
    attack_id: T1087
    name: Account Discovery
  platforms:
    linux:
      sh:
        command: cat /etc/passwd > #{host.user.accounts}
```
then i've created the fact:
```
---
id: 7fd73387-7165-4599-9332-0684c35c168e
name: first-op
facts:
  - trait: remote.host.ip
    value: 0.0.0.0
  - trait: host.user.accounts
    value: /home/ubuntu/stage/exfil/accounts.txt
```
so i expected that the variable would have been replaced with the value when i start an operation with this ability but it isn't. The output is:

> sh: 1: Syntax error: end of file unexpected

If i set the path hard coded in the ability it works. 
Thanks for the help!

**Comment by khyberspache** [comment]
You've stumbled upon what is called "scoping variables."  In order to prune down facts (i.e. only use files discovered on a machine on that specific machine), we block the planner from using variables that begin with `host` from being used unless they are "learned" from that host.  So hard coded facts wouldn't work and that is an intentional design strategy.

If you change the variable to `#{file.user.accounts}` the fact will get rendered properly.
@wbooth implemented a lot of the scoping variable work, so he can offer more suggestions.

**Comment by perra22** [comment]
Thank you for the answer!

**Comment by perra22** [comment]
I've tried to change the fact and variable name to #{file.user.accounts} but it isn't rendered properly.

![Capture](https://user-images.githubusercontent.com/18696951/70034171-0c6baf80-15b1-11ea-80c6-9f2c7e76bd5e.PNG)

![Capture3](https://user-images.githubusercontent.com/18696951/70034350-4fc61e00-15b1-11ea-8941-05cf73662d69.PNG)

![Capture1](https://user-images.githubusercontent.com/18696951/70034174-0d044600-15b1-11ea-8b80-c296277f35f4.PNG)

![Capture2](https://user-images.githubusercontent.com/18696951/70034176-0d044600-15b1-11ea-86a2-5b015fcbdbd0.PNG)

**Comment by wbooth** [comment]
Thanks for all the screen shots, can you post the fact source as well?

**Comment by perra22** [comment]
This is the fact source code:
```
---

id: 7fd73387-7165-4599-9332-0684c35c168e
name: first-op
facts:
  - trait: remote.host.ip
    value: 0.0.0.0
  - trait: file.user.accounts
    value: /home/ubuntu/stage/exfil/accounts.txt

```
and this is the screenshot of the sources:

![Capture4](https://user-images.githubusercontent.com/18696951/70039796-cb789880-15ba-11ea-8855-14c834b50916.PNG)
