### ISSUE TITLE
Learn multiple facts

### ISSUE THREAD

**Issue by perra22** [mitre/caldera#986]
Hi,
is it possible to make Caldera learns multiple facts using different parsers inside the same ability? 
For example:

```
- description: Start LaZagne
  id: 11a936f6-32df-491e-9366-45dcf727d439
  name: Start LaZagne
  platforms:
    linux:
      sh:
        cleanup: sudo rm -r /tmp/LaZagne
        command: cd /tmp/LaZagne/Linux && sudo python3 laZagne.py all
        parsers:
          - plugins.stockpile.app.parsers.basic:
            - source: target.sshCommand
          - plugins.stockpile.app.parsers.laZagne:
            - source: target.example
  tactic: credential-access
  technique:
    attack_id: T1003
    name: ''
```

Enhancement: It would be cool to write the parse command directly in the ability tab instead of the ability file.

I've noticed that if you modify a ".yml" ability file (I've added a parser) and then you make a change inside the ability tab in Caldera the former change is lost.

Thanks.
